services:
  # A Docker web service
  - type: web
    name: quick-ecommerce-api
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quick-ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: FRONTEND_URL
        value: https://quick-ecommerce-frontend.onrender.com

databases:
  - name: quick-ecommerce-db
    plan: free
    databaseName: quickcommerce
    user: quickcommerce_user 